-- Social / campaign layer. Platform-ready post copy generated by the Manager.
-- v1 is a publish kit (draft/scheduled copy + hashtags you copy-paste); actual
-- auto-posting via platform OAuth is a later, human-approved step.

do $$ begin
  create type social_status as enum ('draft', 'scheduled', 'posted');
exception when duplicate_object then null; end $$;

create table if not exists social_posts (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid references projects(id) on delete set null,
  platform      text not null,             -- x, instagram, tiktok, youtube, linkedin, ...
  content       text not null,
  hashtags      text[] not null default '{}',
  status        social_status not null default 'draft',
  scheduled_for timestamptz,
  created_at    timestamptz not null default now()
);

create index if not exists idx_social_project on social_posts(project_id);
create index if not exists idx_social_status on social_posts(status);
create index if not exists idx_social_created on social_posts(created_at desc);

alter table social_posts enable row level security;
